### ISSUE TITLE
Pg-tap on GitHub actions

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-RTP#146]
As a developer
I want to test database functionality on push to github
so that I can ensure data is being saved appropriately.

DoD:
- [ ] determine how much test coverage we want 
- [ ] only update if logged out
- [ ] can only read own records
- [x] pg-tap runs on GitHub actions
- [x] tests are passing
- [x] tests run on push to any branch

To test the database effectively we will need to bring in the testing harness pg-tap

DoD:

 Test runner runs tests
 At least 1 passing test

**Comment by rgreensp** [comment]
Relevant particularly for cases where we expect data to be immutable, or not able to be changed after submission. Can create tech debt card if there is clean-up post launch.

**Comment by rgreensp** [comment]
Find time to discuss what kind of test coverage we want.
