### ISSUE TITLE
Auto-saved notification

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-RTP#165]
### User Story
As a user, I want to know when my responses are saved so that I know I can leave the form and my responses are saved.

### Acceptance Criteria
Given that a user is on a page with input fields, when they enter responses and the responses are automatically saved, then a visual indication that responses are saved will appear at the top right of the page.

**Comment by elliottSlee** [comment]
Determine when to trigger -- API returns successfully when click on continue. So it would reinforce that responses have been saved.
Determine where to place in UI. @elliottSlee @zoeyli-46

**Comment by rgreensp** [comment]
No implemented for RTP. Can consider for future forms.
