### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-RTP#173]
As a program analyst, I want the email address fields to be validated so that I am confident the correct information is input.

Add help text next to field description for desired format enforcement.

**Comment by rgreensp** [comment]
Use native email type of email field.

**Comment by rgreensp** [comment]
Next step - estimate this card.

**Comment by elliottSlee** [comment]
@BryanGK the toolkit says it can have input type set as email which will use a browser's validation. Has this been implemented?

**Comment by BryanGK** [comment]
@elliottSlee can you point me to where it says that?

**Comment by BryanGK** [comment]
@elliottSlee Ah while that is part of the toolkit, that type of element is not implemented on the form-builder. It could be, but at present, is not.
