### ISSUE TITLE
Create and Test Application Data Backup

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-RTP#176]
**Application data** should be backed-up in case of data loss.
- For Dev, Test, and Prod environments.

**Acceptance Criterias**

- [ ] Create backup service
- [ ] Schedule it for once a day (2am)
- [ ] Do a restore to check if it works after 2 days

**Comment by rgreensp** [comment]
@wenzowski - Can you help refine and estimate this one?

**Comment by rgreensp** [comment]
Is there a CITZ-supported corporate solution?

**Comment by BryanGK** [comment]
The common component used doesn't support local backup storage. The CC would be used for mostly for cloud storage solutions.
