### ISSUE TITLE
Get namespace for Metabase

### ISSUE THREAD

**Issue by rgreensp** [bcgov/connectivity-RTP#303]
- [ ] Respond to Olena's email
- [ ] Request name space using self-serve tool

**Comment by rgreensp** [comment]
Requesting namespace to:
- Reuse enterprise Metabase licenses across applications - RTP and Intake
- Separately manage resource usage - takes 2 databases (it's own Petroni set, and its own query string)
- Follow best practice established by other teams

**Comment by matthieu-foucault** [comment]
Looks like this was done a while ago, I have access to metabase namespace in OpenShift
