### ISSUE TITLE
Applicant dashboard wireframe approval

### ISSUE THREAD

**Issue by rgreensp** [bcgov/connectivity-RTP#344]
- [ ] Wireframe of applicant dashboard
- [ ] Add features to backlog so they can be scoped and prioritized - e.g. ability to resume application, start new application, withdraw application

**Comment by rgreensp** [comment]
@elliottSlee - Please link to the wireframe card. Let's have a sprint goal of approving an MVP of the applicant dashboard wireframe, and accompanying features so that we can start development in following sprint.

**Comment by elliottSlee** [comment]
@rgreensp see [CONN-CCBC-portal#51](https://app.zenhub.com/workspaces/connectivity-intake-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/51)
