### ISSUE TITLE
RTP Closed

### ISSUE THREAD

**Issue by rgreensp** [bcgov/connectivity-RTP#347]
Given that a respondent goes to the RTP landing page (https://connectivity-rtp-test.apps.silver.devops.gov.bc.ca/)

When they read the page

Then at the bottom of the text in a new paragraph, it says: "Thank you for your interest in responding to the RTP. The response deadline has now passed. Please direct any further questions to connectingcommunitiesbc@gov.bc.ca." 

And the "Login" Button is grayed out.

**Comment by BryanGK** [comment]
Work done by PR's #348 #349 - CLOSED

**Comment by eazeredo** [comment]
Prod: https://connectivity-rtp.apps.silver.devops.gov.bc.ca/
