### ISSUE TITLE
RTP Application Form

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-RTP#50]
Form to include fields similar to [this](https://www.northerndevelopment.bc.ca/wp-content/uploads/2020/10/NDIT-Pre-Screen-Application-Form-CBC-P4-ERI.pdf) one from NDIT

**Comment by rgreensp** [comment]
The form is made up of three sets of questions:
- Business/contact info
- Zone questions
- Cellular questions

The form (or each section?) ends with a clear path to uploading Geomark files. @elliottSlee? Let's look at user flow.

**Comment by elliottSlee** [comment]
> The form is made up of three sets of questions:
> 
> * Business/contact info
> * Zone questions
> * Cellular questions
> 
> The form (or each section?) ends with a clear path to uploading Geomark files. @elliottSlee? Let's look at user flow.

See Issue #38 for full info on this
