### ISSUE TITLE
SSL certification for HTTPS traffic

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-RTP#80]
If/when we change to a vanity URL we'll need to make changes mentioned below.

> Note that this only works with the *.apps.silver.devops.gov.bc.ca hosts. Whenever your application goes to prod and you have a vanity URL, you'll have to switch it back to passthrough, generate an SSL certificate, and handle the https request yourself. A pattern for this is to use a second container in your pod that runs an Nginx reverse-proxy and does the SSL termination (e.g. https://github.com/bcgov/cas-template-app/tree/develop/nginx-sidecar/helm/nginx-sidecar)

**Comment by rgreensp** [comment]
@wenzowski - Is this necessary for launch?

**Comment by rgreensp** [comment]
Only relevant if we need a vanity URL.
